/api/auth/login:
  post:
    tags:
      - Auth
    summary: Realiza login do usuário
    description: Autentica um employee e retorna tokens JWT
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LoginDTO'
    responses:
      200:
        description: Login realizado com sucesso
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthResponse'
      401:
        description: Credenciais inválidas
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'

/api/auth/logout:
  post:
    tags:
      - Auth
    summary: Realiza logout do usuário
    security:
      - bearerAuth: []
    responses:
      200:
        description: Logout realizado com sucesso
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutResponse'
      401:
        description: Token inválido ou não fornecido