LoginDTO:
  type: object
  required:
    - email
    - password
  properties:
    email:
      type: string
      format: email
      example: admin@gmail.com
    password:
      type: string
      example: pass22

AuthResponse:
  type: object
  properties:
    data:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
        employee:
          type: object
          properties:
            id:
              type: string
              format: uuid
            email:
              type: string
              format: email

LogoutResponse:
  type: object
  properties:
    message:
      type: string
      example: "Logout successful. Token revoked."

ErrorResponse:
  type: object
  properties:
    error:
      type: string